CREATE TABLE perfis (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);


INSERT INTO perfis (nome) VALUES ('ROLE_USER');
INSERT INTO perfis (nome) VALUES ('ROLE_ADMIN');

